#!/usr/bin/env ruby
require 'json'
require 'open3'
require 'pp'
require 'shellwords'

# Converts media files to use container/codec pairings which are compatible with:
# - Google Chrome / Chromecast
# - Microsoft Xbox One
module ConvertForAll
  module_function

  def get_streams(filename)
    stdin, stdout, stderr = Open3.popen3('ffprobe -show_streams -print_format json ' + Shellwords.escape(filename))
    JSON.parse(stdout.read, symbolize_names: true)[:streams]
  end

  def valid_audio_codecs
    ['aac']
  end

  def audio_needs_conversion?(streams)
    valid_streams = streams.select do |s|
      s[:codec_type] == "audio" &&
      valid_audio_codecs.include?(s[:codec_name])
    end
    valid_streams.empty?
  end

  def valid_video_codecs
    ['h264', 'hevc']
  end

  def video_needs_conversion?(streams)
    valid_streams = streams.select do |s|
      s[:codec_type] == "video" &&
      valid_video_codecs.include?(s[:codec_name])
    end
    valid_streams.empty?
  end

  def container_needs_conversion?(filename)
    File.extname(filename) != ".mp4"
  end

  def convert_if_needed(filename)
    streams = get_streams(filename)
    a = audio_needs_conversion?(streams)
    v = video_needs_conversion?(streams)
    c = container_needs_conversion?(filename)

    convert(filename, audio_encode: a, video_encode: v, container_convert: c) if a || v || c
  end

  def convert(filename, opts)
    puts "Converting '#{filename}' with the following options:"
    pp opts

    dir = File.dirname(filename)
    basename = File.basename(filename, ".*") + '-compat.mp4'
    newfile = File.join(dir, basename)

    in_fname = Shellwords.escape(filename)
    out_fname = Shellwords.escape(newfile)

    ffmpeg_vid = 'copy'
    ffmpeg_vid = 'h264' if opts[:video_encode]

    ffmpeg_aud = 'copy'
    ffmpeg_aud = '-c:a aac' if opts[:audio_encode]

    full_ffmpeg_cmd = "ffmpeg -i #{in_fname} -c:v #{ffmpeg_vid} -c:a #{ffmpeg_aud} #{out_fname}"
    puts "Running this ffmpeg incantation:"
    puts full_ffmpeg_cmd
    system(full_ffmpeg_cmd)
  end

  def run(files)
    files.each { |f| convert_if_needed(f) }
  end
end

if ARGF.argv.empty?
  puts "Usage: #{$PROGRAM_NAME} <input_file(s)>"
  exit
end

ConvertForAll.run(ARGF.argv)
